#!/bin/bash
# ============================================================
# Delete topics — connectors, Tableflow, schemas, and topics
# ============================================================
# Steps 1-3 use public Confluent Cloud APIs (run from laptop).
# Step 4 deletes the Kafka topic via the PNI REST endpoint
# through the bastion host (SSH + curl).
#
# Requires:
#   - bastion-key.pem in terraform/confluent-cloud/ (or set BASTION_KEY_PATH)
#   - BASTION_HOST in .env.topics (auto-generated by terraform)
#
# Usage:
#   ./scripts/delete-topics.sh                  # all defaults (orders, customers, pageviews)
#   ./scripts/delete-topics.sh pageviews        # single topic
#
# ============================================================

set -euo pipefail

PYTHON=$(command -v python3 2>/dev/null || echo "python3")

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.topics"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE not found."
  echo "Generate it: cd terraform/confluent-cloud && terraform output -raw topics_env > ../../scripts/.env.topics"
  exit 1
fi

set -a
source "$ENV_FILE"
set +a

# Bastion SSH key — look in common locations
BASTION_KEY_PATH="${BASTION_KEY_PATH:-}"
if [ -z "$BASTION_KEY_PATH" ]; then
  for candidate in \
    "${PROJECT_ROOT}/terraform/confluent-cloud/bastion-key.pem" \
    "${PROJECT_ROOT}/bastion-key.pem" \
    "${HOME}/.ssh/bastion-key.pem"; do
    if [ -f "$candidate" ]; then
      BASTION_KEY_PATH="$candidate"
      break
    fi
  done
fi

if [ -z "$BASTION_KEY_PATH" ]; then
  echo "Error: bastion-key.pem not found."
  echo "Looked in: terraform/confluent-cloud/, project root, ~/.ssh/"
  echo "Set BASTION_KEY_PATH to override."
  exit 1
fi

if [ -z "${BASTION_HOST:-}" ]; then
  echo "Error: BASTION_HOST not set in .env.topics"
  echo "Regenerate: cd terraform/confluent-cloud && terraform output -raw topics_env > ../../scripts/.env.topics"
  exit 1
fi

CC_API="https://api.confluent.cloud"
CONNECT_URL="${CC_API}/connect/v1/environments/${ENVIRONMENT_ID}/clusters/${CLUSTER_ID}/connectors"

# Default topics to delete (all known demo topics)
DEFAULT_TOPICS="orders customers pageviews"

# Build topic list
if [ $# -eq 0 ]; then
  TOPICS="$DEFAULT_TOPICS"
  echo "=== Deleting all demo topics: ${TOPICS} ==="
else
  TOPICS="$*"
  echo "=== Deleting topic(s): ${TOPICS} ==="
fi
echo ""

# --- Step 1: Delete datagen connectors ---
echo "=== Step 1: Deleting Datagen Connectors ==="
for topic in $TOPICS; do
  CONNECTOR_NAME="datagen_${topic}"
  echo "Deleting connector: $CONNECTOR_NAME"
  RESP=$(curl -s -w "\n%{http_code}" -X DELETE "${CONNECT_URL}/${CONNECTOR_NAME}" \
    -u "${CONFLUENT_CLOUD_API_KEY}:${CONFLUENT_CLOUD_API_SECRET}") || true
  HTTP_CODE=$(echo "$RESP" | tail -1)
  BODY=$(echo "$RESP" | head -n -1)
  if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "204" ]; then
    echo "  Deleted."
  elif [ "$HTTP_CODE" = "404" ]; then
    echo "  Not found (already deleted)."
  else
    echo "  HTTP $HTTP_CODE: $BODY"
  fi
done

# --- Step 2: Disable Tableflow ---
echo ""
echo "=== Step 2: Disabling Tableflow ==="
TABLEFLOW_RESP=$(curl -sS -w "\n%{http_code}" \
  "${CC_API}/tableflow/v1/tableflow-topics?spec.kafka_cluster=${CLUSTER_ID}&environment=${ENVIRONMENT_ID}" \
  -u "${TABLEFLOW_API_KEY}:${TABLEFLOW_API_SECRET}") || true
TF_HTTP_CODE=$(echo "$TABLEFLOW_RESP" | tail -1)
TF_BODY=$(echo "$TABLEFLOW_RESP" | head -n -1)

if [ "$TF_HTTP_CODE" != "200" ]; then
  echo "  Failed to list Tableflow topics (HTTP $TF_HTTP_CODE): $TF_BODY"
else
  for topic in $TOPICS; do
    TF_ID=$($PYTHON -c "
import json, sys
data = json.loads(sys.stdin.read())
for t in data.get('data', []):
    if t.get('spec', {}).get('display_name', '') == '$topic':
        print(t.get('id', ''))
        break
" <<< "$TF_BODY" 2>/dev/null) || true

    if [ -z "$TF_ID" ]; then
      echo "  $topic: Tableflow not enabled (already disabled)."
    else
      echo "  $topic: Disabling Tableflow (id: $TF_ID)"
      RESP=$(curl -sS -w "\n%{http_code}" -X DELETE \
        "${CC_API}/tableflow/v1/tableflow-topics/${TF_ID}?environment=${ENVIRONMENT_ID}&spec.kafka_cluster=${CLUSTER_ID}" \
        -u "${TABLEFLOW_API_KEY}:${TABLEFLOW_API_SECRET}") || true
      HTTP_CODE=$(echo "$RESP" | tail -1)
      BODY=$(echo "$RESP" | head -n -1)
      if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "204" ]; then
        echo "    Deleted."
      else
        echo "    HTTP $HTTP_CODE: $BODY"
      fi
    fi
  done
fi

# --- Step 3: Delete schemas ---
echo ""
echo "=== Step 3: Deleting Schemas ==="
for topic in $TOPICS; do
  echo "Deleting schema: ${topic}-value"
  curl -s -o /dev/null -X DELETE \
    "${SCHEMA_REGISTRY_URL}/subjects/${topic}-value" \
    -u "${SCHEMA_REGISTRY_API_KEY}:${SCHEMA_REGISTRY_API_SECRET}" 2>/dev/null || true
  curl -s -o /dev/null -X DELETE \
    "${SCHEMA_REGISTRY_URL}/subjects/${topic}-value?permanent=true" \
    -u "${SCHEMA_REGISTRY_API_KEY}:${SCHEMA_REGISTRY_API_SECRET}" 2>/dev/null || true
  echo "  Done."
done

# --- Step 4: Delete Kafka topics via bastion (PNI REST endpoint) ---
echo ""
echo "=== Step 4: Deleting Kafka Topics (via bastion -> PNI REST) ==="
echo "  Bastion: ec2-user@${BASTION_HOST}"
echo "  PNI REST: ${KAFKA_REST_ENDPOINT}"
echo ""

for topic in $TOPICS; do
  echo "Deleting topic: $topic"
  RESP=$(ssh -i "$BASTION_KEY_PATH" -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
    "ec2-user@${BASTION_HOST}" \
    "curl -s -w '\n%{http_code}' -X DELETE \
      '${KAFKA_REST_ENDPOINT}/kafka/v3/clusters/${CLUSTER_ID}/topics/${topic}' \
      -u '${KAFKA_API_KEY}:${KAFKA_API_SECRET}'" 2>/dev/null) || true
  HTTP_CODE=$(echo "$RESP" | tail -1)
  BODY=$(echo "$RESP" | head -n -1)
  if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "204" ]; then
    echo "  Deleted."
  elif [ "$HTTP_CODE" = "404" ]; then
    echo "  Not found (already deleted)."
  else
    echo "  HTTP $HTTP_CODE: $BODY"
  fi
done

echo ""
echo "=== Done ==="
echo "Run 'python sync.py' to remove tables from Unity Catalog."
